name: Slayers
version: '${version}'
main: me.sedri.slayers.Slayers
api-version: 1.18
authors: [ Sedri ]
depend:
  - LuckPerms
  - Vault
commands:
  slayer:
    description: Main Slayer Command
    aliases:
      - slayers
  sql:
    description: e
